import type { Blueprint } from "@workspace/db";

export function blueprintToMarkdown(b: Blueprint): string {
  const lines: string[] = [];

  lines.push(`# ${b.emoji} ${b.name}`);
  lines.push("");
  lines.push(`> ${b.tagline}`);
  lines.push("");
  lines.push(b.description);
  lines.push("");

  lines.push("## Overview");
  lines.push("");
  lines.push(`- **Category:** ${b.category}`);
  lines.push(`- **Difficulty:** ${b.difficulty}`);
  lines.push(`- **Estimated build time:** ${b.estimatedHours} hours`);
  lines.push(`- **Target audience:** ${b.targetAudience}`);
  lines.push(`- **Original prompt:** _${b.prompt}_`);
  lines.push("");

  if (b.features.length) {
    lines.push("## Features");
    lines.push("");
    b.features.forEach((f) => {
      lines.push(`### ${f.title}`);
      lines.push("");
      lines.push(f.description);
      lines.push("");
    });
  }

  if (b.pages.length) {
    lines.push("## Pages");
    lines.push("");
    lines.push("| Route | Name | Purpose |");
    lines.push("| --- | --- | --- |");
    b.pages.forEach((p) => {
      lines.push(`| \`${p.route}\` | ${p.name} | ${escapePipes(p.purpose)} |`);
    });
    lines.push("");
  }

  if (b.dataModels.length) {
    lines.push("## Data Models");
    lines.push("");
    b.dataModels.forEach((m) => {
      lines.push(`### ${m.name}`);
      lines.push("");
      lines.push(m.description);
      lines.push("");
      if (m.fields.length) {
        lines.push("| Field | Type | Description |");
        lines.push("| --- | --- | --- |");
        m.fields.forEach((field) => {
          lines.push(`| \`${field.name}\` | \`${field.type}\` | ${escapePipes(field.description)} |`);
        });
        lines.push("");
      }
    });
  }

  if (b.userStories.length) {
    lines.push("## User Stories");
    lines.push("");
    b.userStories.forEach((s) => {
      lines.push(`- As a **${s.role}**, I want to ${s.action} so that ${s.benefit}.`);
    });
    lines.push("");
  }

  if (b.techStack.length) {
    lines.push("## Tech Stack");
    lines.push("");
    const byCategory = new Map<string, typeof b.techStack>();
    b.techStack.forEach((t) => {
      const list = byCategory.get(t.category) ?? [];
      list.push(t);
      byCategory.set(t.category, list);
    });
    Array.from(byCategory.entries()).forEach(([category, items]) => {
      lines.push(`### ${category}`);
      lines.push("");
      items.forEach((t) => {
        lines.push(`- **${t.name}** — ${t.reason}`);
      });
      lines.push("");
    });
  }

  if (b.fileStructure.length) {
    lines.push("## File Structure");
    lines.push("");
    lines.push("```");
    b.fileStructure.forEach((node) => {
      const segments = node.path.split("/").filter(Boolean);
      const indent = "  ".repeat(Math.max(0, segments.length - 1));
      const label = segments[segments.length - 1] ?? node.path;
      const suffix = node.kind === "folder" ? "/" : "";
      const purpose = node.purpose ? `  # ${node.purpose}` : "";
      lines.push(`${indent}${label}${suffix}${purpose}`);
    });
    lines.push("```");
    lines.push("");
  }

  if (b.milestones.length) {
    lines.push("## Roadmap");
    lines.push("");
    [...b.milestones]
      .sort((a, c) => a.order - c.order)
      .forEach((m) => {
        lines.push(`### ${m.order}. ${m.title}`);
        lines.push("");
        lines.push(m.description);
        lines.push("");
      });
  }

  lines.push("---");
  lines.push("");
  lines.push(`_Generated by Architect.AI on ${b.createdAt.toISOString().split("T")[0]}._`);
  lines.push("");

  return lines.join("\n");
}

function escapePipes(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ");
}
